name: Publish to npm

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Data pipeline
        run: npm run pipeline

      - name: Type check
        run: npm run tscheck

      - name: Test
        run: npm run test:ci

      - name: Build
        run: npm run build

      - name: Test build
        run: npm run script -- test-build

      - name: Release
        run: npm run release
